# Generated by Django 2.0.2 on 2018-02-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='complement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
